#! /bin/sh

# Keyboard
setxkbmap br &

# Picom
killall picom
picom -b --config ~/.config/picom.conf &

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Dunst (Notifications)
killall dunst
dunst &

# Wallpaper
feh --bg-scale /home/ricardocosta/Pictures/.wallpaper.png

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 2
bspc config window_gap 6
bspc config focus_follows_pointer true
bspc config bottom_padding 0
bspc config split_ratio 0.5
bspc config focused_border_color "#f7768e"
bspc config normal_border_color "#353b45"

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Motrix state=floating
bspc rule -a floorp state=tiled desktop='^2' follow=on

# Polybar
~/.config/polybar/forest/launch.sh --forest &

# Browser
flatpak run one.ablaze.floorp &
