game:
  exe: /mnt/HD/Games/Prefixes/Dark Souls Remastered/drive_c/Program Files (x86)/DODI-Repacks/Dark
    Souls Remastered/DarkSoulsRemastered.exe
  prefix: /mnt/HD/Games/Prefixes/Dark Souls Remastered
